name: COGS108_FA25
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mamba
  - jupyter_core
  - jupyterlab=4.2.4
  - notebook=7.2.1
  - jupyterhub
  - nbclassic=1.1.0
  - ca-certificates
  - certifi
  - openssl
  - altair
  - beautifulsoup4
  - bokeh
  - bottleneck=1.4.2
  - cloudpickle
  - conda-forge::blas[build=openblas]
  - cython
  - dask
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - jupyterlab-git
  - matplotlib-base
  - numba
  - numexpr
  - openpyxl
  - pandas=2.2.3
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels=0.14.4
  - sympy
  - widgetsnbextension
  - xlrd
  - jupyter-pluto-proxy
  - r-base
  - r-caret
  - r-crayon
  - r-devtools
  - r-e1071
  - r-forecast
  - r-hexbin
  - r-htmltools
  - r-htmlwidgets
  - r-irkernel
  - r-nycflights13
  - r-randomforest
  - r-rcurl
  - r-rmarkdown
 # - r-rodbc # No ARM Mac support for this package right now
  - r-rsqlite
  - r-shiny
  - r-tidymodels
  - r-tidyverse
  - rpy2
  # - unixodbc # No Windows support for this package right now
  - pillow
  - typing-extensions
  - tzlocal
  - appdirs
  - gputil
  - mock
  - pytest
  - umap-learn
  - nltk
  - mistune
  - dpkt
  - nose
  - datascience
  - pyarrow
  - jupyter_server=2.14.2
  - jupyterlab_rise
  - jupyter_server_terminals
  - jupyterlab-latex
  - jupyterlab-fasta
  - jupyterlab-geojson
  - nbconvert=7.16.4
  - nbgrader=0.9.3
  - r-markdown
  - r-covr
  - r-git2r
  - r-crosstalk
  - r-dt

